### ISSUE TITLE
Crash when starting game

### ISSUE THREAD

**Issue by Gamerbolts** [doublemoon1119/MahjongCraft#2]
Hello again! I am back with another crash :) I was able to add the bots just fine but when I tried to start game it crashed. Here is the Latest Log and Crash Log. Thank you so much for the quick update last time!
[crash-2022-02-07_21.34.56-server.txt](https://github.com/doublemoon1119/MahjongCraft/files/8020512/crash-2022-02-07_21.34.56-server.txt)
[latest.log](https://github.com/doublemoon1119/MahjongCraft/files/8020513/latest.log)

**Comment by doublemoon1119** [comment]
Thanks for your report. This issue should have been resolved.

**Comment by Gamerbolts** [comment]
It works! Thank you!
