### ISSUE TITLE
跟朋友一起打麻將 都會打到一半伺服器崩潰 失去連線  還有4個人的時候不會出現流局 會直接卡住不開啟新的一局

### ISSUE THREAD

**Issue by love7288** [doublemoon1119/MahjongCraft#6]
---- Minecraft Crash Report ----
// Don't do that.

Time: 2022/6/9 下午9:56
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1685)
	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
	at doublemoon.mahjongcraft.scheduler.server.ServerScheduler.tick(ServerScheduler.kt:21)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:62)
	at net.minecraft.server.MinecraftServer.handler$bgl002$onEndTick(MinecraftServer.java:4332)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:889)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 18, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 3916592704 bytes (3735 MiB) / 11995709440 bytes (11440 MiB) up to 17179869184 bytes (16384 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1b81
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9709
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.40
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.40
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 56904.99
	Virtual memory used (MB): 53582.61
	Swap memory total (MB): 24182.19
	Swap memory used (MB): 4103.68
	JVM Flags: 2 total; -Xmx16G -Xms2G
	Fabric Mods: 
		achievement_plates 1.6.1
		additionaladditions 4.0.2
		additionalbars 3.0.0
		additionalstructures 3.0.3
		adorn 3.5.0+1.18.2
		advanced_runtime_resource_pack 0.5.7
		advdebug 2.3.0
		adventurez 1.4.10
		aqupdcaracal 1.18.2-1.3.8
		aqupdgrizzly 1.18-1.3
		architects_palette 1.7
		architectury 4.4.60
		attributefix 14.0.1
		audioplayer 1.18.2-1.0.2
		autoconfig1u 3.4.0
		awesomeflooring 2.0.0
		backpackmod 1.18.2-3.1.1
		badpackets 0.1.2
		balm-fabric 3.0.0+0
		basicshields 1.3.1-1.18.2
			crowdin-translate 1.4+1.18.2
		bcc fabric-1.0.5
		bedspreads 1.5.0-1.18
		betteranimalsplus 1.18.2-11.0.5
		bhmenu 1.17.1-1.18.2-1.3
		biomemakeover 1.18.2-1.4.22
		blockus 2.4.5+1.18.2
			terraform-wood-api-v1 3.0.0
		bookshelf 13.0.13
		bosses_of_mass_destruction 1.3.7-1.18.2
			maelstrom_library 1.2.4-1.18.2
			multipart_entities 1.1.5-1.18.2
		camsbackpacks 2.11
		capybara 1.0.4
		cardinal-components 4.1.4
			cardinal-components-base 4.1.4
			cardinal-components-block 4.1.4
			cardinal-components-chunk 4.1.4
			cardinal-components-entity 4.1.4
			cardinal-components-item 4.1.4
			cardinal-components-level 4.1.4
			cardinal-components-scoreboard 4.1.4
			cardinal-components-world 4.1.4
		carrier 1.10.0
		charm 4.1.0
			com_moandjiezana_toml_toml4j 0.7.2
		chess 1.2
		clienttweaks 7.1.0
		cloth-api 3.2.64
			cloth-client-events-v0 3.2.64
			cloth-common-events-v1 3.2.64
			cloth-datagen-api-v1 3.2.64
			cloth-utils-v1 3.2.64
		cloth-config 6.2.62
			cloth-basic-math 0.6.1
		clumps 8.0.0+8
		collective-fabric 4.26
			fiber 0.23.0-2
		comforts 1.1.2-1.18.2
		configurableextramobdrops-fabric 1.8
		crafttweaker 9.1.140
			org_javassist_javassist 3.28.0-GA
			org_reflections_reflections 0.10.2
		crawl 0.10.6
			mm 2.3
		creatures_from_the_warmths 2.0.0+1.18.2
		creeperoverhaul 1.3.1
		croptopia 2.0.0
			com_typesafe_config 1.4.1
			io_leangen_geantyref_geantyref 1.3.11
			org_spongepowered_configurate-core 4.1.2
			org_spongepowered_configurate-hocon 4.1.2
		cyti 1.0.5
			team_reborn_energy 2.2.0
		darkpaintings 10.0.1
		dawn 3.3.0
		decor4fabric 1.2
		decorative_blocks 2.1.0
		deepslatecutting 1.3.3
			maybe-data 1.3.1-1.18.2
		disenchanter 0.1.6+1.18
		doom 4.2.11
		dragonloot 1.0.10
		duckling 1.0.4
		dustrial_decor 0.5
		dynview 1.18.2-2.1
		earthtojavamobs 1.8.0+1.18.2
		easymagic 3.3.0
			com_electronwill_night-config_core 3.6.3
			com_electronwill_night-config_toml 3.6.3
		easyshulkerboxes 3.1.1
		ecologics 1.5.4
		editsign 2.3.1
		elementalswords 1.18.2-1.6.2-[FABRIC]
		elytratrinket 3.0.0-1.18.1
		exlinefurniture 2.0.7
		extended_armor_bars 1.2.1
		extragenerators 1.2.1-BETA+1.18
		fabric 0.53.0+1.18.2
			fabric-api-base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1 1.6.0+2373a54560
			fabric-biome-api-v1 8.0.4+7b0f312660
			fabric-command-api-v1 1.1.9+d7c144a860
			fabric-commands-v0 0.2.8+b4f4f6cd60
			fabric-containers-v0 0.1.21+d7c144a860
			fabric-content-registries-v0 3.0.4+d82b939260
			fabric-convention-tags-v1 1.0.1+474e4f7960
			fabric-crash-report-info-v1 0.2.0+a6b0947860
			fabric-dimensions-v1 2.1.17+2540745460
			fabric-entity-events-v1 1.4.8+d7c144a860
			fabric-events-interaction-v0 0.4.19+d7c144a860
			fabric-events-lifecycle-v0 0.2.15+d7c144a860
			fabric-game-rule-api-v1 1.0.13+d7c144a860
			fabric-item-api-v1 1.5.0+85719ab760
			fabric-item-groups-v0 0.3.12+91896a4960
			fabric-lifecycle-events-v1 2.0.3+2d83e92c60
			fabric-loot-tables-v1 1.0.11+d7c144a860
			fabric-mining-level-api-v1 2.1.1+81ea5b3c60
			fabric-networking-api-v1 1.0.21+d882b91560
			fabric-networking-v0 0.3.8+b4f4f6cd60
			fabric-object-builder-api-v1 2.1.1+032c981d60
			fabric-particles-v1 0.2.12+526dc1ac60
			fabric-registry-sync-v0 0.9.8+0d9ab37260
			fabric-rendering-data-attachment-v1 0.3.7+d7c144a860
			fabric-rendering-fluids-v1 2.0.2+54e5b2ec60
			fabric-resource-conditions-api-v1 2.0.3+91b7aa6660
			fabric-resource-loader-v0 0.5.0+2afceb2960
			fabric-screen-handler-api-v1 1.2.0+1f6558e860
			fabric-transfer-api-v1 1.6.1+f4563ac860
			fabric-transitive-access-wideners-v1 1.0.0+bd8a4a1860
		fabric-furnaces 2.1.1-1.18.2
			omega-config 1.2.3-1.18.1
		fabric-language-kotlin 1.7.4+kotlin.1.6.21
			org_jetbrains_kotlin_kotlin-reflect 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.21
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.2
		fabricloader 0.14.6
		fabricshieldlib 1.5.3-1.18
		fallingtree 3.5.1
		feature_nbt_deadlock_be_gone 2.0.0+1.18.2-rc1
		ferritecore 4.2.1
		ffaeop 5.0.0
		forgeconfigapiport 3.2.0
		forgottenrecipes 1.18.1-1.0.0
		friendsandfoes 1.3.4
		ftbchunks 1802.3.6-build.145
		ftblibrary 1802.3.6-build.119
		ftbquests 1802.3.8-build.101
		ftbteams 1802.2.6-build.51
		geckolib3 3.0.42
			com_eliotlash_mclib_mclib 18
			com_eliotlash_molang_molang 18
		geodes 1.4.2
		glassdoor 2.1.0+1.18
		go-fish 1.5.0-1.18.2
		gobber2 2.5.74
			pugh_lib 1.3.0
			pugh_tools 1.2.5
		goblintraders 1.5.1
		goodall 1.0.2
		graveyard 1.8
		guardvillagers 1.18.2-1.0.14
		horizontalpanes 1.1.7+1.18.2
		hwg 1.1.9
		iammusicplayer 3.12
		iceberg 1.0.38
		immersive_weathering 2.4.0
		infusion_table 1.0.5
		ingredient-extension-api 2.0.5
		inmis 2.6.0-1.18.2
		inventorysorter 1.8.6-1.18
			kyrptconfig 1.4.2-1.18
				blue_endless_jankson 1.2.1
		itemfilters 1802.2.7-build.21
		jamlib 0.0.4
		java 18
		justenoughkeys 0.5.3
		kleeslabs 11.0.0
		krypton 0.1.9
			com_velocitypowered_velocity-native 1.1.0-SNAPSHOT
		libraryferret 1.0.3
		lifts 1.4.1-BETA+1.18
		lithium 0.7.9
		llamarama 1.7.0
		londonunderground 1.18.2-3.0.0-1.0.14
		lovely_snails 1.0.4+1.18
		macawsbridgesbyg 1.18.2-1.2
		macawsroofsbyg 1.18.2-1.0
		magiccombatwands 1.0.1
		magnumtorch 3.1.2
		mahjongcraft 0.3.4
			com_github_mahjong4j_mahjong4j 0.3.2
			libgui 5.4.1+1.18.2
				jankson 4.0.0+j1.2.0
				libninepatch 1.1.0
		mavm 1.0.7a
		mbbmod 1.18.2-2.2.1
		mcda 2.0.6
		mcdar 1.4.8
		mcdw 4.3.2
			enchantment_force 0.1.7
			reach-entity-attributes 2.1.1
		mcwbridges 2.0.3
		mcwdoors 1.0.6
		mcwfences 1.0.4
		mcwlights 1.0.3
		mcwpaintings 1.0.3
		mcwroofs 2.1.2
		mcwwindows 2.0.3
		midnightlib 0.4.0
		mightywarhammers 1.1
		minecraft 1.18.2
		minekea 2.7.1
		mo_glass 1.6.1-MC1.18.2
		mobscarecrow 1.2.2
		modid 2.0.0+1.18.2
		modpack_updater 0.0.2
		more-axolotls 1.0.2
		more_babies 0.5.2
		moreachievements 1.0.8
		moredoors 0
		morevillagers-fabric 3.2.0-SNAPSHOT
		mtr 1.18.2-3.0.0
		multibeds 1.2.5
		musicplayer 2.3.3.1
		mythicmounts 1.18.2-7.0
		naturescompass 1.18.2-2.0.3-fabric
		nears 1.1.8
		numismatic-overhaul 0.2.1+1.18
			stacc 1.3.0
		onsoulfire 1.18-3
		otyacraftengine 2.14
		overweight_farming 1.18.2-1.2.0-fabric
		owo 0.7.2+1.18
		oxidized 1.6.4
		pandamc_concreteplus 1.9.3
		patchouli 1.18.2-67-FABRIC
		paxi 1.18.2-Fabric-2.0
		phosphor 0.8.1
		pigsteel 1.7.1
		plushies 1.2
		polymorph 0.0.21-1.18.2
		postmateria 1.0.0-1.18.2
			fiblib 1.3.1+1.18.2
			world-data 1.0.3-1.18.2
		puzzleslib 3.3.1
		quartzelv 2.1.1+1.18
		repurposed_structures 4.1.8+1.18.2
		rightclickharvest 2.0.5
		roughlyenoughitems 8.2.461
		roughlyenoughprofessions 1.0.1
		runelic 11.0.1
		searchlight 1.1.7
		sentimentality3 1.5.0
		shetiphiancore 1.2.10
			myron 1.6.3+1.18.1
		sit 1.18.2-19
		skylorlib 1.3.35
		spark 1.9.1
			fabric-permissions-api-v0 0.1-SNAPSHOT
		spirit 1.2.3
		starterkit-fabric 3.1
		styled-nicknames 1.0.4+1.18
			player-data-api 0.1.0+1.18
		styledchat 1.2.3+1.18
			placeholder-api 1.1.3+1.17.1
		styledplayerlist 2.1.3+1.18
		taterzens 1.9.5
			config2brigadier 1.1.1
			server_translations_api 1.4.12+1.18.2
				packet_tweaker 0.2.0+1.18-pre1
			sgui 1.0.0+1.18.1
		the_aether 1.6.9+1.18.2
			customportalapi 0.0.1-beta50-1.18
			gud_recipe_confidence 1.0.2
			incubus_core 1.6.6+1.18.2
			moretags 3.0.4
		the_bumblezone 5.0.14+1.18.2
			fake-player-api 0.3.0
		thonkutil 2.14.1+1.18
			thonkutil-base 1.12.2+23c1dc2c60
			thonkutil-capes-v1 1.3.2+9e23427060
			thonkutil-customization-v1 1.0.14+9b80223760
			thonkutil-legacy 1.0.20+9b80223760
			thonkutil-modchecker-v1 1.0.12+9b80223760
			thonkutil-potions-v0 1.4.1+9b80223760
			thonkutil-trades-v1 1.1.20+9b80223760
		tolaserblade 1.18.2-0.6.0.0
		toms_storage 1.3.1
		toolsofobsidian 1.18.2-1.5.2-[FABRIC]
		tradernpcs 1.1.1
		tradingpost 3.2.0
		trinketofundying 2.0.1-1.18
		trinkets 3.3.1
		twigs 1.1.3-patch1+1.18.2
		universal_ores 1.2.1
		universalbonemeal 3.0.5
		uteamcore 4.0.0.2
		vanilla_degus 1.3.0
		veinmining 0.0.12-1.18.2
		villager-hats 1.4.0
		villagernames 4.0.4
		visualworkbench 3.3.0
		voicechat 1.18.2-2.2.32
		voidtotem 1.18.2-1.3.1
		voidz 1.0.7
		wandering_collector 1.1.2+mc1.18.2
			tweed4_annotated 1.3.0
			tweed4_base 1.5.0+mc1.18.2
			tweed4_data 1.2.1+mc1.18.2
			tweed4_data_hjson 1.1.0
		wands 2.5_mc1.18.2
		waystones 2.5.3
		windchimes 1.2.0
		worldedit 7.2.10+1742f98
		wthit 4.10.3
		xaerominimap 22.7.0
		xaeroworldmap 1.21.2
		yigd 1.3.5
		yungsapi 1.18.2-Fabric-2.0.8
		yungsbridges 1.18.2-Fabric-2.1.0
		yungsextras 1.18.2-Fabric-2.1.0
		zihlaunchpads 1.2.0
	Server Running: true
	Player Count: 3 / 20; [class_3222['huangzeongyi'/964607, l='ServerLevel[world]', x=28.50, y=21.05, z=-71.50], class_3222['EachHarp5181321'/970154, l='ServerLevel[world]', x=30.50, y=21.05, z=-73.50], class_3222['Kojirah'/974031, l='ServerLevel[world]', x=29.14, y=22.00, z=-73.64]]
	Data Packs: vanilla, Fabric Mods, file/Mob+Health+Bar+[1.5.1]+[1.17.x].zip (incompatible)
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by doublemoon1119** [comment]
感謝你的回饋
崩潰這個問題我應該是處理好了 0c70c9dd65569211a2e746515a8ae194b8966ac2
流局卡住的問題，再麻煩你在遊戲卡住的時候，看看後台有沒有跳出錯誤訊息，再跟我回報
