### ISSUE TITLE
unreasonable furitens

### ISSUE THREAD

**Issue by Kimji-project** [doublemoon1119/MahjongCraft#7]
playing MC 1.19.2, and this mod 0.3.7

i'm not good at english and chinese, so i'm gonna replace report to link.

https://imgur.com/a/EyPHrbQ

and kyuushu kyuuhai counts all of 幺九牌

anyway, i really appreciate for good mod. looking forward to play mahjong with my friend in MC

**Comment by doublemoon1119** [comment]
Thanks for reporting the error.
Enjoy playing Mahjong with your friends in Minecraft!
